defaults:
  - chunker: semantic_splitter
  - retriever: multiQuery
  - rag: ChatBotRag

embedder:
  type: huggingface
  model_name: HIT-TMG/KaLM-embedding-multilingual-mini-v1
  # powerful multilingual model => More language => token's decomposed heavily => More to embed => this model is better than Alibaba NLP models

llm:
  base_url: https://chat.ai.linagora.exaion.com/v1/
  name: meta-llama-31-8b-it
  api_key: ${oc.env:API_KEY}
  max_tokens: 1024
  temperature: 0.0

vectordb:
  host: localhost
  port: 6333
  connector_name: qdrant
  collection_name: vdb95
  hybrid_mode: true

reranker:
  model_name: jinaai/jina-colbert-v2
  top_k: 6

verbose:
  verbose: true
  level: INFO

paths:
  root_dir: ${oc.env:ROOT_DIR}
  base_dir: ${oc.env:BASE_DIR}
  prompts_dir: ${oc.env:PROMPTS_DIR}

prompt:
  rag_sys_pmpt: rag_sys_prompt_template.txt # rag_sys_pmpt_tmpl_ifa.txt
  context_pmpt_tmpl: contextualize_prompt_template.txt